[build]
  command = "yarn install && yarn build"  # Adjust this command based on your build process
  publish = "dist"  # Adjust this to your output directory
  node_version = "19.x"  # Specify the Node.js version
